PSP directory successfully set: /storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/data/pseudos_module/espresso/esp_pseudos_old
PSP directory successfully set: /storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/data/pseudos_module/espresso/nninc/pbe/van
Abort(941707023) on node 0 (rank 0 in comm 0): Fatal error in PMPI_Comm_split: Other MPI error, error stack:
PMPI_Comm_split(499).....: MPI_Comm_split(comm=0xc400003c, color=0, key=0, new_comm=0x7ffffffedf40) failed
PMPI_Comm_split(481).....: 
MPIR_Comm_split_impl(384): 
MPIR_Comm_commit(598)....: 
MPIR_Info_alloc(61)......: Out of memory (unable to allocate a 'MPI_Info')
[mpiexec@atl1-1-02-015-31-r.pace.gatech.edu] HYDT_bscd_pbs_wait_for_completion (tools/bootstrap/external/pbs_wait.c:67): tm_poll(obit_event) failed with TM error 17002
[mpiexec@atl1-1-02-015-31-r.pace.gatech.edu] HYDT_bsci_wait_for_completion (tools/bootstrap/src/bsci_wait.c:23): launcher returned error waiting for completion
[proxy:0:1@atl1-1-02-015-4-l.pace.gatech.edu] HYD_pmcd_pmip_control_cmd_cb (pm/pmiserv/pmip_cb.c:911): assert (!closed) failed
[proxy:0:1@atl1-1-02-015-4-l.pace.gatech.edu] HYDT_dmxu_poll_wait_for_event (tools/demux/demux_poll.c:76): callback returned erro[proxy:0:0@atl1-1-02-015-31-r.pace.gatech.edu] HYD_pmcd_pmip_control_cmd_cb (pm/pmiserv/pmip_cb.c:911): assert (!closed) failed
[proxy:0:0@atl1-1-02-015-31-r.pace.gatech.edu] HYDT_dmxu_poll_wait_for_event (tools/demux/demux_poll.c:76): callback returned err status
[proxy:0:1@atl1-1-02-015-4-l.pace.gatech.edu] main (pm/pmiserv/pmip.c:202): demux engine error waiting for event
ror status
[proxy:0:0@atl1-1-02-015-31-r.pace.gatech.edu] main (pm/pmiserv/pmip.c:202): demux engine error waiting for event
Traceback (most recent call last):
  File "run.py", line 28, in <module>
    relax.run(fmax=0.05)
  File "/storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/gits/dev/ase-latest/ase/optimize/optimize.py", line 298, in run
    return Dynamics.run(self)
  File "/storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/gits/dev/ase-latest/ase/optimize/optimize.py", line 185, in run
    for converged in Dynamics.irun(self):
  File "/storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/gits/dev/ase-latest/ase/optimize/optimize.py", line 164, in irun
    self.step()
  File "/storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/gits/dev/ase-latest/ase/optimize/bfgslinesearch.py", line 124, in step
    c2=self.c2, stpmax=self.stpmax)
  File "/storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/gits/dev/ase-latest/ase/utils/linesearch.py", line 57, in _line_search
    fval = func(xk + stp * pk, *args)
  File "/storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/gits/dev/ase-latest/ase/optimize/bfgslinesearch.py", line 172, in func
    force_consistent=self.force_consistent) / self.alpha)
  File "/storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/gits/dev/ase-latest/ase/atoms.py", line 730, in get_potential_energy
    self, force_consistent=force_consistent)
  File "/storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/gits/dev/ggusmao-espresso/espresso/espresso.py", line 2340, in get_potential_energy
    self.update(atoms)
  File "/storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/gits/dev/ggusmao-espresso/espresso/iespresso.py", line 592, in update
    self.calculate(atoms, properties)
  File "/storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/gits/dev/ggusmao-espresso/espresso/iespresso.py", line 646, in calculate
    results = self.server.calculate(atoms,properties)
  File "/storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/gits/dev/ggusmao-espresso/espresso/iespresso.py", line 457, in calculate
    return self.protocol.calculate(atoms.positions, atoms.cell, properties)
  File "/storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/gits/dev/ggusmao-espresso/espresso/iespresso.py", line 290, in calculate
    r = self.ionic_step(positions, cell, properties)
  File "/storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/gits/dev/ggusmao-espresso/espresso/iespresso.py", line 274, in ionic_step
    msg = self.status()
  File "/storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/gits/dev/ggusmao-espresso/espresso/iespresso.py", line 233, in status
    msg = self.recvmsg()
  File "/storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/gits/dev/ggusmao-espresso/espresso/iespresso.py", line 122, in recvmsg
    msg = self._recvall(12)
  File "/storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/gits/dev/ggusmao-espresso/espresso/iespresso.py", line 111, in _recvall
    chunk = self.socket.recv(remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
PSP directory successfully set: /storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/data/pseudos_module/espresso/esp_pseudos_old
PSP directory successfully set: /storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/data/pseudos_module/espresso/nninc/pbe/van
PSP directory successfully set: /storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/data/pseudos_module/espresso/esp_pseudos_old
PSP directory successfully set: /storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/data/pseudos_module/espresso/nninc/pbe/van
PSP directory successfully set: /storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/data/pseudos_module/espresso/esp_pseudos_old
PSP directory successfully set: /storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/data/pseudos_module/espresso/nninc/pbe/van
Traceback (most recent call last):
  File "/storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/gits/dev/ase-latest/ase/optimize/optimize.py", line 344, in load
    return read_json(fd, always_array=False)
  File "/storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/gits/dev/ase-latest/ase/utils/__init__.py", line 483, in iofunc
    obj = func(fd, *args, **kwargs)
  File "/storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/gits/dev/ase-latest/ase/io/jsonio.py", line 153, in read_json
    dct = decode(fd.read(), always_array=always_array)
  File "/storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/gits/dev/ase-latest/ase/io/jsonio.py", line 144, in decode
    obj = mydecode(txt)
  File "/usr/local/pace-apps/manual/packages/anaconda3/2020.02/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/pace-apps/manual/packages/anaconda3/2020.02/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 65537 (char 65536)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run.py", line 27, in <module>
    restart='opt.pckl')
  File "/storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/gits/dev/ase-latest/ase/optimize/bfgslinesearch.py", line 85, in __init__
    master, force_consistent=force_consistent)
  File "/storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/gits/dev/ase-latest/ase/optimize/optimize.py", line 273, in __init__
    self.read()
  File "/storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/gits/dev/ase-latest/ase/optimize/bfgslinesearch.py", line 88, in read
    self.r0, self.g0, self.e0, self.task, self.H = self.load()
  File "/storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/gits/dev/ase-latest/ase/optimize/optimize.py", line 348, in load
    raise RestartError(msg) from ex
ase.optimize.optimize.RestartError: Could not decode restart file as JSON.  You may need to delete the restart file opt.pckl

mkdir fail: [2] No such file or directory
forrtl: No such file or directory
forrtl: No such file or directory
forrtl: No such file or directory
forrtl: No such file or directory
forrtl: No such file or directory
forrtl: No such file or directory
forrtl: No such file or directory
forrtl: No such file or directory
forrtl: No such file or directory
forrtl: No such file or directory
forrtl: No such file or directory
forrtl: No such file or directory
forrtl: No such file or directory
forrtl: No such file or directory
forrtl: No such file or directory
forrtl: No such file or directory
forrtl: severe (29): file not found, unit 99, file .//CRASH
Image              PC                Routine            Line        Source             
pw.x               0000000001C61EDB  Unknown               Unknown  Unknown
pw.x               0000000001C80FC0  Unknown               Unknown  Unknown
pw.x               00000000017EFF93  Unknown               Unknown  Unknown
pw.x               0000000000F52AEC  Unknown               Unknown  Unknown
pw.x               000000000054D250  Unknown               Unknown  Unknown
pw.x               00000000006B7CCF  Unknown               Unknown  Unknown
pw.x               0000000000413820  Unknown               Unknown  Unknown
pw.x               0000000000412F90  Unknown               Unknown  Unknown
pw.x               0000000000412DD2  Unknown               Unknown  Unknown
libc-2.17.so       00002AAAB39E2555  __libc_start_main     Unknown  Unknown
pw.x               0000000000412CE9  Unknown               Unknown  Unknown
forrtl: severe (29): file not found, unit 99, file .//CRASH
Image              PC                Routine            Line        Source             
pw.x               0000000001C61EDB  Unknown               Unknown  Unknown
pw.x               0000000001C80FC0  Unknown               Unknown  Unknown
pw.x               00000000017EFF93  Unknown               Unknown  Unknown
pw.x               0000000000F52AEC  Unknown               Unknown  Unknown
pw.x               000000000054D250  Unknown               Unknown  Unknown
pw.x               00000000006B7CCF  Unknown               Unknown  Unknown
pw.x               0000000000413820  Unknown               Unknown  Unknown
pw.x               0000000000412F90  Unknown               Unknown  Unknown
pw.x               0000000000412DD2  Unknown               Unknown  Unknown
libc-2.17.so       00002AAAB39E2555  __libc_start_main     Unknown  Unknown
pw.x               0000000000412CE9  Unknown               Unknown  Unknown
forrtl: severe (29): file not found, unit 99, file .//CRASH
Image              PC                Routine            Line        Source             
pw.x               0000000001C61EDB  Unknown               Unknown  Unknown
pw.x               0000000001C80FC0  Unknown               Unknown  Unknown
pw.x               00000000017EFF93  Unknown               Unknown  Unknown
pw.x               0000000000F52AEC  Unknown               Unknown  Unknown
pw.x               000000000054D250  Unknown               Unknown  Unknown
pw.x               00000000006B7CCF  Unknown               Unknown  Unknown
pw.x               0000000000413820  Unknown               Unknown  Unknown
pw.x               0000000000412F90  Unknown               Unknown  Unknown
pw.x               0000000000412DD2  Unknown               Unknown  Unknown
libc-2.17.so       00002AAAB39E2555  __libc_start_main     Unknown  Unknown
pw.x               0000000000412CE9  Unknown               Unknown  Unknown
forrtl: severe (29): file not found, unit 99, file .//CRASH
Image              PC                Routine            Line        Source             
pw.x               0000000001C61EDB  Unknown               Unknown  Unknown
pw.x               0000000001C80FC0  Unknown               Unknown  Unknown
pw.x               00000000017EFF93  Unknown               Unknown  Unknown
pw.x               0000000000F52AEC  Unknown               Unknown  Unknown
pw.x               000000000054D250  Unknown               Unknown  Unknown
pw.x               00000000006B7CCF  Unknown               Unknown  Unknown
pw.x               0000000000413820  Unknown               Unknown  Unknown
pw.x               0000000000412F90  Unknown               Unknown  Unknown
pw.x               0000000000412DD2  Unknown               Unknown  Unknown
libc-2.17.so       00002AAAB39E2555  __libc_start_main     Unknown  Unknown
pw.x               0000000000412CE9  Unknown               Unknown  Unknown
forrtl: severe (29): file not found, unit 99, file .//CRASH
Image              PC                Routine            Line        Source             
pw.x               0000000001C61EDB  Unknown               Unknown  Unknown
pw.x               0000000001C80FC0  Unknown               Unknown  Unknown
pw.x               00000000017EFF93  Unknown               Unknown  Unknown
pw.x               0000000000F52AEC  Unknown               Unknown  Unknown
pw.x               000000000054D250  Unknown               Unknown  Unknown
pw.x               00000000006B7CCF  Unknown               Unknown  Unknown
pw.x               0000000000413820  Unknown               Unknown  Unknown
pw.x               0000000000412F90  Unknown               Unknown  Unknown
pw.x               0000000000412DD2  Unknown               Unknown  Unknown
libc-2.17.so       00002AAAB39E2555  __libc_start_main     Unknown  Unknown
pw.x               0000000000412CE9  Unknown               Unknown  Unknown
forrtl: severe (29): file not found, unit 99, file .//CRASH
Image              PC                Routine            Line        Source             
pw.x               0000000001C61EDB  Unknown               Unknown  Unknown
pw.x               0000000001C80FC0  Unknown               Unknown  Unknown
pw.x               00000000017EFF93  Unknown               Unknown  Unknown
pw.x               0000000000F52AEC  Unknown               Unknown  Unknown
pw.x               000000000054D250  Unknown               Unknown  Unknown
pw.x               00000000006B7CCF  Unknown               Unknown  Unknown
pw.x               0000000000413820  Unknown               Unknown  Unknown
pw.x               0000000000412F90  Unknown               Unknown  Unknown
pw.x               0000000000412DD2  Unknown               Unknown  Unknown
libc-2.17.so       00002AAAB39E2555  __libc_start_main     Unknown  Unknown
pw.x               0000000000412CE9  Unknown               Unknown  Unknown
forrtl: severe (29): file not found, unit 99, file .//CRASH
Image              PC                Routine            Line        Source             
pw.x               0000000001C61EDB  Unknown               Unknown  Unknown
pw.x               0000000001C80FC0  Unknown               Unknown  Unknown
pw.x               00000000017EFF93  Unknown               Unknown  Unknown
pw.x               0000000000F52AEC  Unknown               Unknown  Unknown
pw.x               000000000054D250  Unknown               Unknown  Unknown
pw.x               00000000006B7CCF  Unknown               Unknown  Unknown
pw.x               0000000000413820  Unknown               Unknown  Unknown
pw.x               0000000000412F90  Unknown               Unknown  Unknown
pw.x               0000000000412DD2  Unknown               Unknown  Unknown
libc-2.17.so       00002AAAB39E2555  __libc_start_main     Unknown  Unknown
pw.x               0000000000412CE9  Unknown               Unknown  Unknown
forrtl: severe (29): file not found, unit 99, file .//CRASH
Image              PC                Routine            Line        Source             
pw.x               0000000001C61EDB  Unknown               Unknown  Unknown
pw.x               0000000001C80FC0  Unknown               Unknown  Unknown
pw.x               00000000017EFF93  Unknown               Unknown  Unknown
pw.x               0000000000F52AEC  Unknown               Unknown  Unknown
pw.x               000000000054D250  Unknown               Unknown  Unknown
pw.x               00000000006B7CCF  Unknown               Unknown  Unknown
pw.x               0000000000413820  Unknown               Unknown  Unknown
pw.x               0000000000412F90  Unknown               Unknown  Unknown
pw.x               0000000000412DD2  Unknown               Unknown  Unknown
libc-2.17.so       00002AAAB39E2555  __libc_start_main     Unknown  Unknown
pw.x               0000000000412CE9  Unknown               Unknown  Unknown
forrtl: severe (29): file not found, unit 99, file .//CRASH
Image              PC                Routine            Line        Source             
pw.x               0000000001C61EDB  Unknown               Unknown  Unknown
pw.x               0000000001C80FC0  Unknown               Unknown  Unknown
pw.x               00000000017EFF93  Unknown               Unknown  Unknown
pw.x               0000000000F52AEC  Unknown               Unknown  Unknown
pw.x               000000000054D250  Unknown               Unknown  Unknown
pw.x               00000000006B7CCF  Unknown               Unknown  Unknown
pw.x               0000000000413820  Unknown               Unknown  Unknown
pw.x               0000000000412F90  Unknown               Unknown  Unknown
pw.x               0000000000412DD2  Unknown               Unknown  Unknown
libc-2.17.so       00002AAAB39E2555  __libc_start_main     Unknown  Unknown
pw.x               0000000000412CE9  Unknown               Unknown  Unknown
forrtl: severe (29): file not found, unit 99, file .//CRASH
Image              PC                Routine            Line        Source             
pw.x               0000000001C61EDB  Unknown               Unknown  Unknown
pw.x               0000000001C80FC0  Unknown               Unknown  Unknown
pw.x               00000000017EFF93  Unknown               Unknown  Unknown
pw.x               0000000000F52AEC  Unknown               Unknown  Unknown
pw.x               000000000054D250  Unknown               Unknown  Unknown
pw.x               00000000006B7CCF  Unknown               Unknown  Unknown
pw.x               0000000000413820  Unknown               Unknown  Unknown
pw.x               0000000000412F90  Unknown               Unknown  Unknown
pw.x               0000000000412DD2  Unknown               Unknown  Unknown
libc-2.17.so       00002AAAB39E2555  __libc_start_main     Unknown  Unknown
pw.x               0000000000412CE9  Unknown               Unknown  Unknown
forrtl: severe (29): file not found, unit 99, file .//CRASH
Image              PC                Routine            Line        Source             
pw.x               0000000001C61EDB  Unknown               Unknown  Unknown
pw.x               0000000001C80FC0  Unknown               Unknown  Unknown
pw.x               00000000017EFF93  Unknown               Unknown  Unknown
pw.x               0000000000F52AEC  Unknown               Unknown  Unknown
pw.x               000000000054D250  Unknown               Unknown  Unknown
pw.x               00000000006B7CCF  Unknown               Unknown  Unknown
pw.x               0000000000413820  Unknown               Unknown  Unknown
pw.x               0000000000412F90  Unknown               Unknown  Unknown
pw.x               0000000000412DD2  Unknown               Unknown  Unknown
libc-2.17.so       00002AAAB39E2555  __libc_start_main     Unknown  Unknown
pw.x               0000000000412CE9  Unknown               Unknown  Unknown
forrtl: severe (29): file not found, unit 99, file .//CRASH
Image              PC                Routine            Line        Source             
pw.x               0000000001C61EDB  Unknown               Unknown  Unknown
pw.x               0000000001C80FC0  Unknown               Unknown  Unknown
pw.x               00000000017EFF93  Unknown               Unknown  Unknown
pw.x               0000000000F52AEC  Unknown               Unknown  Unknown
pw.x               000000000054D250  Unknown               Unknown  Unknown
pw.x               00000000006B7CCF  Unknown               Unknown  Unknown
pw.x               0000000000413820  Unknown               Unknown  Unknown
pw.x               0000000000412F90  Unknown               Unknown  Unknown
pw.x               0000000000412DD2  Unknown               Unknown  Unknown
libc-2.17.so       00002AAAB39E2555  __libc_start_main     Unknown  Unknown
pw.x               0000000000412CE9  Unknown               Unknown  Unknown
forrtl: severe (29): file not found, unit 99, file .//CRASH
Image              PC                Routine            Line        Source             
pw.x               0000000001C61EDB  Unknown               Unknown  Unknown
pw.x               0000000001C80FC0  Unknown               Unknown  Unknown
pw.x               00000000017EFF93  Unknown               Unknown  Unknown
pw.x               0000000000F52AEC  Unknown               Unknown  Unknown
pw.x               000000000054D250  Unknown               Unknown  Unknown
pw.x               00000000006B7CCF  Unknown               Unknown  Unknown
pw.x               0000000000413820  Unknown               Unknown  Unknown
pw.x               0000000000412F90  Unknown               Unknown  Unknown
pw.x               0000000000412DD2  Unknown               Unknown  Unknown
libc-2.17.so       00002AAAB39E2555  __libc_start_main     Unknown  Unknown
pw.x               0000000000412CE9  Unknown               Unknown  Unknown
forrtl: severe (29): file not found, unit 99, file .//CRASH
Image              PC                Routine            Line        Source             
pw.x               0000000001C61EDB  Unknown               Unknown  Unknown
pw.x               0000000001C80FC0  Unknown               Unknown  Unknown
pw.x               00000000017EFF93  Unknown               Unknown  Unknown
pw.x               0000000000F52AEC  Unknown               Unknown  Unknown
pw.x               000000000054D250  Unknown               Unknown  Unknown
pw.x               00000000006B7CCF  Unknown               Unknown  Unknown
pw.x               0000000000413820  Unknown               Unknown  Unknown
pw.x               0000000000412F90  Unknown               Unknown  Unknown
pw.x               0000000000412DD2  Unknown               Unknown  Unknown
libc-2.17.so       00002AAAB39E2555  __libc_start_main     Unknown  Unknown
pw.x               0000000000412CE9  Unknown               Unknown  Unknown
forrtl: severe (29): file not found, unit 99, file .//CRASH
Image              PC                Routine            Line        Source             
pw.x               0000000001C61EDB  Unknown               Unknown  Unknown
pw.x               0000000001C80FC0  Unknown               Unknown  Unknown
pw.x               00000000017EFF93  Unknown               Unknown  Unknown
pw.x               0000000000F52AEC  Unknown               Unknown  Unknown
pw.x               000000000054D250  Unknown               Unknown  Unknown
pw.x               00000000006B7CCF  Unknown               Unknown  Unknown
pw.x               0000000000413820  Unknown               Unknown  Unknown
pw.x               0000000000412F90  Unknown               Unknown  Unknown
pw.x               0000000000412DD2  Unknown               Unknown  Unknown
libc-2.17.so       00002AAAB39E2555  __libc_start_main     Unknown  Unknown
pw.x               0000000000412CE9  Unknown               Unknown  Unknown
forrtl: severe (29): file not found, unit 99, file .//CRASH
Image              PC                Routine            Line        Source             
pw.x               0000000001C61EDB  Unknown               Unknown  Unknown
pw.x               0000000001C80FC0  Unknown               Unknown  Unknown
pw.x               00000000017EFF93  Unknown               Unknown  Unknown
pw.x               0000000000F52AEC  Unknown               Unknown  Unknown
pw.x               000000000054D250  Unknown               Unknown  Unknown
pw.x               00000000006B7CCF  Unknown               Unknown  Unknown
pw.x               0000000000413820  Unknown               Unknown  Unknown
pw.x               0000000000412F90  Unknown               Unknown  Unknown
pw.x               0000000000412DD2  Unknown               Unknown  Unknown
libc-2.17.so       00002AAAB39E2555  __libc_start_main     Unknown  Unknown
pw.x               0000000000412CE9  Unknown               Unknown  Unknown
[proxy:0:0@atl1-1-03-004-2-r.pace.gatech.edu] HYD_pmcd_pmip_control_cmd_cb (pm/pmiserv/pmip_cb.c:911): assert (!closed) failed
[proxy:0:0@atl1-1-03-004-2-r.pace.gatech.edu] HYDT_dmxu_poll_wait_for_event (tools/demux/demux_poll.c:76): callback returned error status
[proxy:0:0@atl1-1-03-004-2-r.pace.gatech.edu] main (pm/pmiserv/pmip.c:202): demux engine error waiting for event
PSP directory successfully set: /storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/data/pseudos_module/espresso/esp_pseudos_old
PSP directory successfully set: /storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/data/pseudos_module/espresso/nninc/pbe/van
Traceback (most recent call last):
  File "/storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/gits/dev/ase-latest/ase/optimize/optimize.py", line 344, in load
    return read_json(fd, always_array=False)
  File "/storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/gits/dev/ase-latest/ase/utils/__init__.py", line 483, in iofunc
    obj = func(fd, *args, **kwargs)
  File "/storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/gits/dev/ase-latest/ase/io/jsonio.py", line 153, in read_json
    dct = decode(fd.read(), always_array=always_array)
  File "/storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/gits/dev/ase-latest/ase/io/jsonio.py", line 144, in decode
    obj = mydecode(txt)
  File "/usr/local/pace-apps/manual/packages/anaconda3/2020.02/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/pace-apps/manual/packages/anaconda3/2020.02/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 65537 (char 65536)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run.py", line 27, in <module>
    restart='opt.pckl')
  File "/storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/gits/dev/ase-latest/ase/optimize/bfgslinesearch.py", line 85, in __init__
    master, force_consistent=force_consistent)
  File "/storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/gits/dev/ase-latest/ase/optimize/optimize.py", line 273, in __init__
    self.read()
  File "/storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/gits/dev/ase-latest/ase/optimize/bfgslinesearch.py", line 88, in read
    self.r0, self.g0, self.e0, self.task, self.H = self.load()
  File "/storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/gits/dev/ase-latest/ase/optimize/optimize.py", line 348, in load
    raise RestartError(msg) from ex
ase.optimize.optimize.RestartError: Could not decode restart file as JSON.  You may need to delete the restart file opt.pckl
[proxy:0:0@atl1-1-02-002-6-l.pace.gatech.edu] HYD_pmcd_pmip_control_cmd_cb (pm/pmiserv/pmip_cb.c:911): assert (!closed) failed
[proxy:0:0@atl1-1-02-002-6-l.pace.gatech.edu] HYDT_dmxu_poll_wait_for_event (tools/demux/demux_poll.c:76): callback returned error status
[proxy:0:0@atl1-1-02-002-6-l.pace.gatech.edu] main (pm/pmiserv/pmip.c:202): demux engine error waiting for event
PSP directory successfully set: /storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/data/pseudos_module/espresso/esp_pseudos_old
PSP directory successfully set: /storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/data/pseudos_module/espresso/nninc/pbe/van
Traceback (most recent call last):
  File "run.py", line 7, in <module>
    image = read('opt.traj')
  File "/storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/gits/dev/ase-latest/ase/io/formats.py", line 729, in read
    format = format or filetype(filename, read=isinstance(filename, str))
  File "/storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/gits/dev/ase-latest/ase/io/formats.py", line 935, in filetype
    raise UnknownFileTypeError('Empty file: ' + filename)    # type: ignore
ase.io.formats.UnknownFileTypeError: Empty file: opt.traj
PSP directory successfully set: /storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/data/pseudos_module/espresso/esp_pseudos_old
PSP directory successfully set: /storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/data/pseudos_module/espresso/nninc/pbe/van
Traceback (most recent call last):
  File "/storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/gits/dev/ase-latest/ase/optimize/optimize.py", line 344, in load
    return read_json(fd, always_array=False)
  File "/storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/gits/dev/ase-latest/ase/utils/__init__.py", line 483, in iofunc
    obj = func(fd, *args, **kwargs)
  File "/storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/gits/dev/ase-latest/ase/io/jsonio.py", line 153, in read_json
    dct = decode(fd.read(), always_array=always_array)
  File "/storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/gits/dev/ase-latest/ase/io/jsonio.py", line 144, in decode
    obj = mydecode(txt)
  File "/usr/local/pace-apps/manual/packages/anaconda3/2020.02/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/pace-apps/manual/packages/anaconda3/2020.02/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 65537 (char 65536)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run.py", line 27, in <module>
    restart='opt.pckl')
  File "/storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/gits/dev/ase-latest/ase/optimize/bfgslinesearch.py", line 85, in __init__
    master, force_consistent=force_consistent)
  File "/storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/gits/dev/ase-latest/ase/optimize/optimize.py", line 273, in __init__
    self.read()
  File "/storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/gits/dev/ase-latest/ase/optimize/bfgslinesearch.py", line 88, in read
    self.r0, self.g0, self.e0, self.task, self.H = self.load()
  File "/storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/gits/dev/ase-latest/ase/optimize/optimize.py", line 348, in load
    raise RestartError(msg) from ex
ase.optimize.optimize.RestartError: Could not decode restart file as JSON.  You may need to delete the restart file opt.pckl

mkdir fail: [2] No such file or directory
forrtl: No such file or directory
forrtl: No such file or directory
forrtl: No such file or directory
forrtl: No such file or directory
forrtl: No such file or directory
forrtl: No such file or directory
forrtl: No such file or directory
forrtl: No such file or directory
forrtl: No such file or directory
forrtl: No such file or directory
forrtl: No such file or directory
forrtl: No such file or directory
forrtl: No such file or directory
forrtl: No such file or directory
forrtl: No such file or directory
forrtl: No such file or directory
forrtl: severe (29): file not found, unit 99, file .//CRASH
Image              PC                Routine            Line        Source             
pw.x               0000000001C61EDB  Unknown               Unknown  Unknown
pw.x               0000000001C80FC0  Unknown               Unknown  Unknown
pw.x               00000000017EFF93  Unknown               Unknown  Unknown
pw.x               0000000000F52AEC  Unknown               Unknown  Unknown
pw.x               000000000054D250  Unknown               Unknown  Unknown
pw.x               00000000006B7CCF  Unknown               Unknown  Unknown
pw.x               0000000000413820  Unknown               Unknown  Unknown
pw.x               0000000000412F90  Unknown               Unknown  Unknown
pw.x               0000000000412DD2  Unknown               Unknown  Unknown
libc-2.17.so       00002AAAB39E2555  __libc_start_main     Unknown  Unknown
pw.x               0000000000412CE9  Unknown               Unknown  Unknown
forrtl: severe (29): file not found, unit 99, file .//CRASH
Image              PC                Routine            Line        Source             
pw.x               0000000001C61EDB  Unknown               Unknown  Unknown
pw.x               0000000001C80FC0  Unknown               Unknown  Unknown
pw.x               00000000017EFF93  Unknown               Unknown  Unknown
pw.x               0000000000F52AEC  Unknown               Unknown  Unknown
pw.x               000000000054D250  Unknown               Unknown  Unknown
pw.x               00000000006B7CCF  Unknown               Unknown  Unknown
pw.x               0000000000413820  Unknown               Unknown  Unknown
pw.x               0000000000412F90  Unknown               Unknown  Unknown
pw.x               0000000000412DD2  Unknown               Unknown  Unknown
libc-2.17.so       00002AAAB39E2555  __libc_start_main     Unknown  Unknown
pw.x               0000000000412CE9  Unknown               Unknown  Unknown
forrtl: severe (29): file not found, unit 99, file .//CRASH
Image              PC                Routine            Line        Source             
pw.x               0000000001C61EDB  Unknown               Unknown  Unknown
pw.x               0000000001C80FC0  Unknown               Unknown  Unknown
pw.x               00000000017EFF93  Unknown               Unknown  Unknown
pw.x               0000000000F52AEC  Unknown               Unknown  Unknown
pw.x               000000000054D250  Unknown               Unknown  Unknown
pw.x               00000000006B7CCF  Unknown               Unknown  Unknown
pw.x               0000000000413820  Unknown               Unknown  Unknown
pw.x               0000000000412F90  Unknown               Unknown  Unknown
pw.x               0000000000412DD2  Unknown               Unknown  Unknown
libc-2.17.so       00002AAAB39E2555  __libc_start_main     Unknown  Unknown
pw.x               0000000000412CE9  Unknown               Unknown  Unknown
forrtl: severe (29): file not found, unit 99, file .//CRASH
Image              PC                Routine            Line        Source             
pw.x               0000000001C61EDB  Unknown               Unknown  Unknown
pw.x               0000000001C80FC0  Unknown               Unknown  Unknown
pw.x               00000000017EFF93  Unknown               Unknown  Unknown
pw.x               0000000000F52AEC  Unknown               Unknown  Unknown
pw.x               000000000054D250  Unknown               Unknown  Unknown
pw.x               00000000006B7CCF  Unknown               Unknown  Unknown
pw.x               0000000000413820  Unknown               Unknown  Unknown
pw.x               0000000000412F90  Unknown               Unknown  Unknown
pw.x               0000000000412DD2  Unknown               Unknown  Unknown
libc-2.17.so       00002AAAB39E2555  __libc_start_main     Unknown  Unknown
pw.x               0000000000412CE9  Unknown               Unknown  Unknown
forrtl: severe (29): file not found, unit 99, file .//CRASH
Image              PC                Routine            Line        Source             
pw.x               0000000001C61EDB  Unknown               Unknown  Unknown
pw.x               0000000001C80FC0  Unknown               Unknown  Unknown
pw.x               00000000017EFF93  Unknown               Unknown  Unknown
pw.x               0000000000F52AEC  Unknown               Unknown  Unknown
pw.x               000000000054D250  Unknown               Unknown  Unknown
pw.x               00000000006B7CCF  Unknown               Unknown  Unknown
pw.x               0000000000413820  Unknown               Unknown  Unknown
pw.x               0000000000412F90  Unknown               Unknown  Unknown
pw.x               0000000000412DD2  Unknown               Unknown  Unknown
libc-2.17.so       00002AAAB39E2555  __libc_start_main     Unknown  Unknown
pw.x               0000000000412CE9  Unknown               Unknown  Unknown
forrtl: severe (29): file not found, unit 99, file .//CRASH
Image              PC                Routine            Line        Source             
pw.x               0000000001C61EDB  Unknown               Unknown  Unknown
pw.x               0000000001C80FC0  Unknown               Unknown  Unknown
pw.x               00000000017EFF93  Unknown               Unknown  Unknown
pw.x               0000000000F52AEC  Unknown               Unknown  Unknown
pw.x               000000000054D250  Unknown               Unknown  Unknown
pw.x               00000000006B7CCF  Unknown               Unknown  Unknown
pw.x               0000000000413820  Unknown               Unknown  Unknown
pw.x               0000000000412F90  Unknown               Unknown  Unknown
pw.x               0000000000412DD2  Unknown               Unknown  Unknown
libc-2.17.so       00002AAAB39E2555  __libc_start_main     Unknown  Unknown
pw.x               0000000000412CE9  Unknown               Unknown  Unknown
forrtl: severe (29): file not found, unit 99, file .//CRASH
Image              PC                Routine            Line        Source             
pw.x               0000000001C61EDB  Unknown               Unknown  Unknown
pw.x               0000000001C80FC0  Unknown               Unknown  Unknown
pw.x               00000000017EFF93  Unknown               Unknown  Unknown
pw.x               0000000000F52AEC  Unknown               Unknown  Unknown
pw.x               000000000054D250  Unknown               Unknown  Unknown
pw.x               00000000006B7CCF  Unknown               Unknown  Unknown
pw.x               0000000000413820  Unknown               Unknown  Unknown
pw.x               0000000000412F90  Unknown               Unknown  Unknown
pw.x               0000000000412DD2  Unknown               Unknown  Unknown
libc-2.17.so       00002AAAB39E2555  __libc_start_main     Unknown  Unknown
pw.x               0000000000412CE9  Unknown               Unknown  Unknown
forrtl: severe (29): file not found, unit 99, file .//CRASH
Image              PC                Routine            Line        Source             
pw.x               0000000001C61EDB  Unknown               Unknown  Unknown
pw.x               0000000001C80FC0  Unknown               Unknown  Unknown
pw.x               00000000017EFF93  Unknown               Unknown  Unknown
pw.x               0000000000F52AEC  Unknown               Unknown  Unknown
pw.x               000000000054D250  Unknown               Unknown  Unknown
pw.x               00000000006B7CCF  Unknown               Unknown  Unknown
pw.x               0000000000413820  Unknown               Unknown  Unknown
pw.x               0000000000412F90  Unknown               Unknown  Unknown
pw.x               0000000000412DD2  Unknown               Unknown  Unknown
libc-2.17.so       00002AAAB39E2555  __libc_start_main     Unknown  Unknown
pw.x               0000000000412CE9  Unknown               Unknown  Unknown
forrtl: severe (29): file not found, unit 99, file .//CRASH
Image              PC                Routine            Line        Source             
pw.x               0000000001C61EDB  Unknown               Unknown  Unknown
pw.x               0000000001C80FC0  Unknown               Unknown  Unknown
pw.x               00000000017EFF93  Unknown               Unknown  Unknown
pw.x               0000000000F52AEC  Unknown               Unknown  Unknown
pw.x               000000000054D250  Unknown               Unknown  Unknown
pw.x               00000000006B7CCF  Unknown               Unknown  Unknown
pw.x               0000000000413820  Unknown               Unknown  Unknown
pw.x               0000000000412F90  Unknown               Unknown  Unknown
pw.x               0000000000412DD2  Unknown               Unknown  Unknown
libc-2.17.so       00002AAAB39E2555  __libc_start_main     Unknown  Unknown
pw.x               0000000000412CE9  Unknown               Unknown  Unknown
forrtl: severe (29): file not found, unit 99, file .//CRASH
Image              PC                Routine            Line        Source             
pw.x               0000000001C61EDB  Unknown               Unknown  Unknown
pw.x               0000000001C80FC0  Unknown               Unknown  Unknown
pw.x               00000000017EFF93  Unknown               Unknown  Unknown
pw.x               0000000000F52AEC  Unknown               Unknown  Unknown
pw.x               000000000054D250  Unknown               Unknown  Unknown
pw.x               00000000006B7CCF  Unknown               Unknown  Unknown
pw.x               0000000000413820  Unknown               Unknown  Unknown
pw.x               0000000000412F90  Unknown               Unknown  Unknown
pw.x               0000000000412DD2  Unknown               Unknown  Unknown
libc-2.17.so       00002AAAB39E2555  __libc_start_main     Unknown  Unknown
pw.x               0000000000412CE9  Unknown               Unknown  Unknown
forrtl: severe (29): file not found, unit 99, file .//CRASH
Image              PC                Routine            Line        Source             
pw.x               0000000001C61EDB  Unknown               Unknown  Unknown
pw.x               0000000001C80FC0  Unknown               Unknown  Unknown
pw.x               00000000017EFF93  Unknown               Unknown  Unknown
pw.x               0000000000F52AEC  Unknown               Unknown  Unknown
pw.x               000000000054D250  Unknown               Unknown  Unknown
pw.x               00000000006B7CCF  Unknown               Unknown  Unknown
pw.x               0000000000413820  Unknown               Unknown  Unknown
pw.x               0000000000412F90  Unknown               Unknown  Unknown
pw.x               0000000000412DD2  Unknown               Unknown  Unknown
libc-2.17.so       00002AAAB39E2555  __libc_start_main     Unknown  Unknown
pw.x               0000000000412CE9  Unknown               Unknown  Unknown
forrtl: severe (29): file not found, unit 99, file .//CRASH
Image              PC                Routine            Line        Source             
pw.x               0000000001C61EDB  Unknown               Unknown  Unknown
pw.x               0000000001C80FC0  Unknown               Unknown  Unknown
pw.x               00000000017EFF93  Unknown               Unknown  Unknown
pw.x               0000000000F52AEC  Unknown               Unknown  Unknown
pw.x               000000000054D250  Unknown               Unknown  Unknown
pw.x               00000000006B7CCF  Unknown               Unknown  Unknown
pw.x               0000000000413820  Unknown               Unknown  Unknown
pw.x               0000000000412F90  Unknown               Unknown  Unknown
pw.x               0000000000412DD2  Unknown               Unknown  Unknown
libc-2.17.so       00002AAAB39E2555  __libc_start_main     Unknown  Unknown
pw.x               0000000000412CE9  Unknown               Unknown  Unknown
forrtl: severe (29): file not found, unit 99, file .//CRASH
Image              PC                Routine            Line        Source             
pw.x               0000000001C61EDB  Unknown               Unknown  Unknown
pw.x               0000000001C80FC0  Unknown               Unknown  Unknown
pw.x               00000000017EFF93  Unknown               Unknown  Unknown
pw.x               0000000000F52AEC  Unknown               Unknown  Unknown
pw.x               000000000054D250  Unknown               Unknown  Unknown
pw.x               00000000006B7CCF  Unknown               Unknown  Unknown
pw.x               0000000000413820  Unknown               Unknown  Unknown
pw.x               0000000000412F90  Unknown               Unknown  Unknown
pw.x               0000000000412DD2  Unknown               Unknown  Unknown
libc-2.17.so       00002AAAB39E2555  __libc_start_main     Unknown  Unknown
pw.x               0000000000412CE9  Unknown               Unknown  Unknown
forrtl: severe (29): file not found, unit 99, file .//CRASH
Image              PC                Routine            Line        Source             
pw.x               0000000001C61EDB  Unknown               Unknown  Unknown
pw.x               0000000001C80FC0  Unknown               Unknown  Unknown
pw.x               00000000017EFF93  Unknown               Unknown  Unknown
pw.x               0000000000F52AEC  Unknown               Unknown  Unknown
pw.x               000000000054D250  Unknown               Unknown  Unknown
pw.x               00000000006B7CCF  Unknown               Unknown  Unknown
pw.x               0000000000413820  Unknown               Unknown  Unknown
pw.x               0000000000412F90  Unknown               Unknown  Unknown
pw.x               0000000000412DD2  Unknown               Unknown  Unknown
libc-2.17.so       00002AAAB39E2555  __libc_start_main     Unknown  Unknown
pw.x               0000000000412CE9  Unknown               Unknown  Unknown
forrtl: severe (29): file not found, unit 99, file .//CRASH
Image              PC                Routine            Line        Source             
pw.x               0000000001C61EDB  Unknown               Unknown  Unknown
pw.x               0000000001C80FC0  Unknown               Unknown  Unknown
pw.x               00000000017EFF93  Unknown               Unknown  Unknown
pw.x               0000000000F52AEC  Unknown               Unknown  Unknown
pw.x               000000000054D250  Unknown               Unknown  Unknown
pw.x               00000000006B7CCF  Unknown               Unknown  Unknown
pw.x               0000000000413820  Unknown               Unknown  Unknown
pw.x               0000000000412F90  Unknown               Unknown  Unknown
pw.x               0000000000412DD2  Unknown               Unknown  Unknown
libc-2.17.so       00002AAAB39E2555  __libc_start_main     Unknown  Unknown
pw.x               0000000000412CE9  Unknown               Unknown  Unknown
PSP directory successfully set: /storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/data/pseudos_module/espresso/esp_pseudos_old
PSP directory successfully set: /storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/data/pseudos_module/espresso/nninc/pbe/van
Traceback (most recent call last):
  File "/storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/gits/dev/ase-latest/ase/optimize/optimize.py", line 344, in load
    return read_json(fd, always_array=False)
  File "/storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/gits/dev/ase-latest/ase/utils/__init__.py", line 483, in iofunc
    obj = func(fd, *args, **kwargs)
  File "/storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/gits/dev/ase-latest/ase/io/jsonio.py", line 153, in read_json
    dct = decode(fd.read(), always_array=always_array)
  File "/storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/gits/dev/ase-latest/ase/io/jsonio.py", line 144, in decode
    obj = mydecode(txt)
  File "/usr/local/pace-apps/manual/packages/anaconda3/2020.02/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/pace-apps/manual/packages/anaconda3/2020.02/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 65537 (char 65536)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run.py", line 26, in <module>
    restart='opt.pckl')
  File "/storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/gits/dev/ase-latest/ase/optimize/bfgslinesearch.py", line 85, in __init__
    master, force_consistent=force_consistent)
  File "/storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/gits/dev/ase-latest/ase/optimize/optimize.py", line 273, in __init__
    self.read()
  File "/storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/gits/dev/ase-latest/ase/optimize/bfgslinesearch.py", line 88, in read
    self.r0, self.g0, self.e0, self.task, self.H = self.load()
  File "/storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/gits/dev/ase-latest/ase/optimize/optimize.py", line 348, in load
    raise RestartError(msg) from ex
ase.optimize.optimize.RestartError: Could not decode restart file as JSON.  You may need to delete the restart file opt.pckl
[proxy:0:0@atl1-1-02-012-33-l.pace.gatech.edu] HYD_pmcd_pmip_control_cmd_cb (pm/pmiserv/pmip_cb.c:911): assert (!closed) failed
[proxy:0:0@atl1-1-02-012-33-l.pace.gatech.edu] HYDT_dmxu_poll_wait_for_event (tools/demux/demux_poll.c:76): callback returned error status
[proxy:0:0@atl1-1-02-012-33-l.pace.gatech.edu] main (pm/pmiserv/pmip.c:202): demux engine error waiting for event
PSP directory successfully set: /storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/data/pseudos_module/espresso/esp_pseudos_old
PSP directory successfully set: /storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/data/pseudos_module/espresso/nninc/pbe/van
Traceback (most recent call last):
  File "/storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/gits/dev/ase-latest/ase/optimize/optimize.py", line 344, in load
    return read_json(fd, always_array=False)
  File "/storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/gits/dev/ase-latest/ase/utils/__init__.py", line 483, in iofunc
    obj = func(fd, *args, **kwargs)
  File "/storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/gits/dev/ase-latest/ase/io/jsonio.py", line 153, in read_json
    dct = decode(fd.read(), always_array=always_array)
  File "/storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/gits/dev/ase-latest/ase/io/jsonio.py", line 144, in decode
    obj = mydecode(txt)
  File "/usr/local/pace-apps/manual/packages/anaconda3/2020.02/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/pace-apps/manual/packages/anaconda3/2020.02/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 65537 (char 65536)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run.py", line 26, in <module>
    restart='opt.pckl')
  File "/storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/gits/dev/ase-latest/ase/optimize/bfgslinesearch.py", line 85, in __init__
    master, force_consistent=force_consistent)
  File "/storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/gits/dev/ase-latest/ase/optimize/optimize.py", line 273, in __init__
    self.read()
  File "/storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/gits/dev/ase-latest/ase/optimize/bfgslinesearch.py", line 88, in read
    self.r0, self.g0, self.e0, self.task, self.H = self.load()
  File "/storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/gits/dev/ase-latest/ase/optimize/optimize.py", line 348, in load
    raise RestartError(msg) from ex
ase.optimize.optimize.RestartError: Could not decode restart file as JSON.  You may need to delete the restart file opt.pckl
forrtl: No such file or directory
forrtl: severe (29): file not found, unit 4, file .//fort.4
Image              PC                Routine            Line        Source             
pw.x               0000000001C61EDB  Unknown               Unknown  Unknown
pw.x               0000000001CC0DD9  Unknown               Unknown  Unknown
pw.x               0000000001BDA037  Unknown               Unknown  Unknown
pw.x               0000000001BC8D0F  Unknown               Unknown  Unknown
pw.x               0000000001BB6779  Unknown               Unknown  Unknown
pw.x               00000000010BF170  Unknown               Unknown  Unknown
pw.x               00000000006BBFBE  Unknown               Unknown  Unknown
pw.x               00000000006B7BB1  Unknown               Unknown  Unknown
pw.x               0000000000413820  Unknown               Unknown  Unknown
pw.x               0000000000412F90  Unknown               Unknown  Unknown
pw.x               0000000000412DD2  Unknown               Unknown  Unknown
libc-2.17.so       00002AAAB39E2555  __libc_start_main     Unknown  Unknown
pw.x               0000000000412CE9  Unknown               Unknown  Unknown
[proxy:0:0@atl1-1-02-014-26-l.pace.gatech.edu] HYD_pmcd_pmip_control_cmd_cb (pm/pmiserv/pmip_cb.c:911): assert (!closed) failed
[proxy:0:0@atl1-1-02-014-26-l.pace.gatech.edu] HYDT_dmxu_poll_wait_for_event (tools/demux/demux_poll.c:76): callback returned error status
[proxy:0:0@atl1-1-02-014-26-l.pace.gatech.edu] main (pm/pmiserv/pmip.c:202): demux engine error waiting for event
PSP directory successfully set: /storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/data/pseudos_module/espresso/esp_pseudos_old
PSP directory successfully set: /storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/data/pseudos_module/espresso/nninc/pbe/van
Traceback (most recent call last):
  File "/storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/gits/dev/ase-latest/ase/optimize/optimize.py", line 344, in load
    return read_json(fd, always_array=False)
  File "/storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/gits/dev/ase-latest/ase/utils/__init__.py", line 483, in iofunc
    obj = func(fd, *args, **kwargs)
  File "/storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/gits/dev/ase-latest/ase/io/jsonio.py", line 153, in read_json
    dct = decode(fd.read(), always_array=always_array)
  File "/storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/gits/dev/ase-latest/ase/io/jsonio.py", line 144, in decode
    obj = mydecode(txt)
  File "/usr/local/pace-apps/manual/packages/anaconda3/2020.02/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/pace-apps/manual/packages/anaconda3/2020.02/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 65537 (char 65536)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run.py", line 26, in <module>
    restart='opt.pckl')
  File "/storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/gits/dev/ase-latest/ase/optimize/bfgslinesearch.py", line 85, in __init__
    master, force_consistent=force_consistent)
  File "/storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/gits/dev/ase-latest/ase/optimize/optimize.py", line 273, in __init__
    self.read()
  File "/storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/gits/dev/ase-latest/ase/optimize/bfgslinesearch.py", line 88, in read
    self.r0, self.g0, self.e0, self.task, self.H = self.load()
  File "/storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/gits/dev/ase-latest/ase/optimize/optimize.py", line 348, in load
    raise RestartError(msg) from ex
ase.optimize.optimize.RestartError: Could not decode restart file as JSON.  You may need to delete the restart file opt.pckl
[proxy:0:0@atl1-1-02-014-18-l.pace.gatech.edu] HYD_pmcd_pmip_control_cmd_cb (pm/pmiserv/pmip_cb.c:911): assert (!closed) failed
[proxy:0:0@atl1-1-02-014-18-l.pace.gatech.edu] HYDT_dmxu_poll_wait_for_event (tools/demux/demux_poll.c:76): callback returned error status
[proxy:0:0@atl1-1-02-014-18-l.pace.gatech.edu] main (pm/pmiserv/pmip.c:202): demux engine error waiting for event
PSP directory successfully set: /storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/data/pseudos_module/espresso/esp_pseudos_old
PSP directory successfully set: /storage/coda1/p-amedford6/0/shared/rich_project_chbe-medford/medford-share/data/pseudos_module/espresso/nninc/pbe/van
